version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: mirisbowring/texlive_ctan_full:2019
    steps:
      - checkout
      - run: git config --add http.sslverify --type bool 'false for github.com'  
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: ~/dist
