version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: mirisbowring/texlive_ctan_full
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: ~/dist
